import type { SpmDependency, GeneratedFile } from "./types";

function xmlEscape(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

export function defaultBundleId(targetName: string): string {
  const sanitized = targetName.toLowerCase().replace(/[^a-z0-9]/g, "");
  return `app.${sanitized || "myapp"}.ios`;
}

export function makeInfoPlist(targetName: string, projectName: string): string {
  const displayName = xmlEscape(projectName);
  const bundleName = xmlEscape(targetName);
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>$(DEVELOPMENT_LANGUAGE)</string>
    <key>CFBundleExecutable</key>
    <string>$(EXECUTABLE_NAME)</string>
    <key>CFBundleIdentifier</key>
    <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleDisplayName</key>
    <string>${displayName}</string>
    <key>CFBundleName</key>
    <string>${bundleName}</string>
    <key>CFBundlePackageType</key>
    <string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>LSRequiresIPhoneOS</key>
    <true/>
    <key>ITSAppUsesNonExemptEncryption</key>
    <false/>
    <key>UIApplicationSupportsIndirectInputEvents</key>
    <true/>
    <key>UILaunchScreen</key>
    <dict>
        <key>UIColorName</key>
        <string>AccentColor</string>
    </dict>
    <key>UIRequiredDeviceCapabilities</key>
    <array>
        <string>arm64</string>
    </array>
    <key>UISupportedInterfaceOrientations</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
        <string>UIInterfaceOrientationLandscapeLeft</string>
        <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
    <key>UISupportedInterfaceOrientations~ipad</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
        <string>UIInterfaceOrientationPortraitUpsideDown</string>
        <string>UIInterfaceOrientationLandscapeLeft</string>
        <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
</dict>
</plist>`;
}

function yamlEscape(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

export function makeProjectYml(
  targetName: string,
  projectName: string,
  bundleId: string,
  spmDependencies: SpmDependency[],
): string {
  const packagesBlock = spmDependencies.length
    ? "packages:\n" +
      spmDependencies
        .map(
          d =>
            `  ${d.packageName}:\n    url: ${d.url}\n    from: ${d.version}`,
        )
        .join("\n") +
      "\n"
    : "";

  const targetSpmDeps = spmDependencies.length
    ? spmDependencies
        .flatMap(d =>
          d.productNames.map(
            pn => `      - package: ${d.packageName}\n        product: ${pn}`,
          ),
        )
        .join("\n") + "\n"
    : "";

  return `# Generated by promptiOS. Run \`xcodegen generate\` (brew install xcodegen)
# to materialize ${targetName}.xcodeproj from this spec, then open it in Xcode.
name: ${targetName}
options:
  bundleIdPrefix: ${bundleId.split(".").slice(0, -1).join(".") || "app.myapp"}
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true
settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_LANGUAGE: en
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    GENERATE_INFOPLIST_FILE: NO
${packagesBlock}targets:
  ${targetName}:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: ${targetName}
    info:
      path: ${targetName}/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${bundleId}
        PRODUCT_NAME: "${yamlEscape(projectName)}"
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_FILE: ${targetName}/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
${targetSpmDeps.length > 0 ? `    dependencies:\n${targetSpmDeps}` : ""}schemes:
  ${targetName}:
    build:
      targets:
        ${targetName}: all
    run:
      config: Debug
    archive:
      config: Release
`;
}

export function makeAssetsContentsJson(): string {
  return `{
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
`;
}

export function makeAppIconContentsJson(): string {
  return `{
  "images" : [
    {
      "filename" : "Icon-1024.png",
      "idiom" : "universal",
      "platform" : "ios",
      "size" : "1024x1024"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
`;
}

export function makeAccentColorContentsJson(): string {
  return `{
  "colors" : [
    {
      "color" : {
        "color-space" : "srgb",
        "components" : {
          "alpha" : "1.000",
          "blue" : "0.937",
          "green" : "0.388",
          "red" : "0.000"
        }
      },
      "idiom" : "universal"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
`;
}

export function makeAppIconReadme(): string {
  return `# App Icon

Drop a 1024×1024 PNG named **Icon-1024.png** into this folder before
archiving for the App Store. Xcode 14+ generates all the smaller icon
sizes from this single file at build time.

Requirements (App Store):
- Exactly 1024×1024 px, PNG, no alpha channel, sRGB.
- Square — Apple applies the rounded mask automatically.
- No transparency, no large flat backgrounds that match the system
  wallpaper.

Until you add Icon-1024.png the app will still build and run in the
simulator, but App Store validation will reject the archive with
"Missing app icon".
`;
}

export function makeAppStoreReadme(targetName: string, projectName: string, bundleId: string): string {
  return `# ${projectName}

Generated by promptiOS. This project is structured as a real iOS App target
(via [XcodeGen](https://github.com/yonaskolb/XcodeGen)) so it can be
submitted to the App Store with no architectural changes.

## 1. One-time setup

\`\`\`bash
brew install xcodegen
\`\`\`

## 2. Generate the Xcode project

From the project root:

\`\`\`bash
xcodegen generate
open ${targetName}.xcodeproj
\`\`\`

This produces a fresh \`${targetName}.xcodeproj\` from \`project.yml\`. Re-run
\`xcodegen generate\` whenever you add or remove source files — the project
file is checked into git as the *source of truth output*, but \`project.yml\`
is the source of truth *input*.

## 3. Run on a simulator

In Xcode: pick an iPhone simulator → ⌘R.

## 4. Get App Store-ready

The project is preconfigured with everything App Store Connect requires
*except* the things only you can fill in:

| Step | Where | What to do |
| ---- | ----- | ---------- |
| Bundle Identifier | \`project.yml\` (\`PRODUCT_BUNDLE_IDENTIFIER\`) — currently \`${bundleId}\` | Change to a unique reverse-DNS string you own, e.g. \`com.yourcompany.${targetName.toLowerCase()}\`. Re-run \`xcodegen generate\` after editing. |
| Signing team | Xcode → Target → Signing & Capabilities | Pick your Apple Developer team. Leave "Automatically manage signing" on. |
| App icon | \`${targetName}/Assets.xcassets/AppIcon.appiconset/Icon-1024.png\` | Drop a 1024×1024 PNG (no alpha) here before archiving. |
| Display name | \`project.yml\` → \`PRODUCT_NAME\` and \`${targetName}/Info.plist\` → \`CFBundleDisplayName\` | Already set to "${projectName}". Change if you want the home-screen label different from the project name. |
| Privacy strings | \`${targetName}/Info.plist\` | If your app uses Camera, Microphone, Location, Contacts, Photos, etc. you **must** add the matching \`NS*UsageDescription\` key explaining why. App Store rejects apps that use these APIs without a usage string. |

The following App Store essentials are **already** wired up for you:

- \`ITSAppUsesNonExemptEncryption=false\` (skips the export-compliance prompt for HTTPS-only apps).
- \`LSRequiresIPhoneOS=true\` and \`UIRequiredDeviceCapabilities=[arm64]\`.
- iPhone + iPad device family, modern \`UILaunchScreen\` dictionary, supported orientations.
- iOS 17.0 deployment target, Swift 5.9, Automatic signing.
- Asset catalog with \`AppIcon\` and \`AccentColor\` slots.

## 5. Archive & ship

1. In Xcode set the destination to **Any iOS Device (arm64)**.
2. Bump the build number under Target → General if this is a re-upload.
3. **Product → Archive** (Release configuration is wired up via the \`${targetName}\` scheme).
4. In the Organizer that opens, **Validate App** first, then **Distribute App → App Store Connect → Upload**.
5. Create the matching app record at https://appstoreconnect.apple.com → Apps → +.
6. Once the build appears in TestFlight (10–60 min), invite testers, fill in the App Store listing (description, screenshots, privacy questionnaire), and submit for review.

The in-app **App Store guide** has the long-form walkthrough, including
common rejection reasons.
`;
}

export function normalizeIosProject(
  files: GeneratedFile[],
  targetName: string,
  projectName: string,
  spmDependencies: SpmDependency[],
): GeneratedFile[] {
  const sourcesPrefix = `${targetName}/`;
  const bundleId = defaultBundleId(targetName);

  const swiftFiles: GeneratedFile[] = [];
  let userReadme: GeneratedFile | null = null;

  for (const f of files) {
    const basename = f.filepath.split("/").pop() ?? f.filename;
    const lower = basename.toLowerCase();

    if (lower === "package.swift") continue;
    if (lower === "info.plist") continue;
    if (lower === "project.yml") continue;
    if (lower === "contents.json") continue;
    if (lower === "readme.md") {
      userReadme = { ...f, filepath: "NOTES.md", filename: "NOTES.md" };
      continue;
    }

    if (f.language === "swift" || f.filename.endsWith(".swift")) {
      const swiftBasename = basename.endsWith(".swift") ? basename : `${basename}.swift`;
      swiftFiles.push({ ...f, filepath: `${sourcesPrefix}${swiftBasename}`, filename: swiftBasename });
    }
  }

  const seenBasenames = new Map<string, number>();
  const deduplicatedSwift = swiftFiles.map((f) => {
    const count = seenBasenames.get(f.filename) ?? 0;
    seenBasenames.set(f.filename, count + 1);
    if (count > 0) {
      const withoutExt = f.filename.replace(/\.swift$/, "");
      const newBasename = `${withoutExt}_${count}.swift`;
      return { ...f, filepath: `${sourcesPrefix}${newBasename}`, filename: newBasename };
    }
    return f;
  });

  const infoPlistFile: GeneratedFile = {
    filename: "Info.plist",
    filepath: `${sourcesPrefix}Info.plist`,
    language: "xml",
    content: makeInfoPlist(targetName, projectName),
  };

  const projectYmlFile: GeneratedFile = {
    filename: "project.yml",
    filepath: "project.yml",
    language: "yaml",
    content: makeProjectYml(targetName, projectName, bundleId, spmDependencies),
  };

  const readmeFile: GeneratedFile = {
    filename: "README.md",
    filepath: "README.md",
    language: "markdown",
    content: makeAppStoreReadme(targetName, projectName, bundleId),
  };

  const assetCatalogContents: GeneratedFile = {
    filename: "Contents.json",
    filepath: `${sourcesPrefix}Assets.xcassets/Contents.json`,
    language: "json",
    content: makeAssetsContentsJson(),
  };
  const appIconContents: GeneratedFile = {
    filename: "Contents.json",
    filepath: `${sourcesPrefix}Assets.xcassets/AppIcon.appiconset/Contents.json`,
    language: "json",
    content: makeAppIconContentsJson(),
  };
  const appIconReadme: GeneratedFile = {
    filename: "README.md",
    filepath: `${sourcesPrefix}Assets.xcassets/AppIcon.appiconset/README.md`,
    language: "markdown",
    content: makeAppIconReadme(),
  };
  const accentColorContents: GeneratedFile = {
    filename: "Contents.json",
    filepath: `${sourcesPrefix}Assets.xcassets/AccentColor.colorset/Contents.json`,
    language: "json",
    content: makeAccentColorContentsJson(),
  };

  const result: GeneratedFile[] = [
    projectYmlFile,
    readmeFile,
    ...deduplicatedSwift,
    infoPlistFile,
    assetCatalogContents,
    appIconContents,
    appIconReadme,
    accentColorContents,
  ];
  if (userReadme) result.push(userReadme);
  return result;
}
